name: Test
on:
  pull_request:

jobs:
  this_always_succeeds:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"

  this_always_fails_3:
    runs-on: ubuntu-latest
    steps:
    - name: Long error message
      run: |
        for ((i=100000;i>=0;--i))
        do
          echo "Error $i!"
        done
        exit 1
