name: Test
on:
  pull_request:

jobs:
  this_always_succeeds:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"

  this_always_fails_3:
    runs-on: ubuntu-latest
    steps:
    - name: First Long message
      run: |
        for ((i=1000;i>=0;--i))
        do
          echo "Line $i"
        done
    - name: Second Long message
      run: |
        for ((i=1000;i>=0;--i))
        do
          echo "Line $i"
        done
    - name: Third Long message
      run: |
        for ((i=1000;i>=0;--i))
        do
          echo "Line $i"
        done
    - name: Fourth Long message
      run: |
        for ((i=1000;i>=0;--i))
        do
          echo "Line $i"
        done
    - name: Error out
      run: |
        echo "Hello World"
        exit 1
