name: Test
on:
  push:
  pull_request:

jobs:
  this_always_succeeds:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"

  this_always_fails_2:
    runs-on: ubuntu-latest
    steps:
    - name: Generate an Error
      run: test 5 -eq 5

  this_always_fails_1:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"
    - name: Error out
      run: |
        echo "No error for this PR!"
        sleep 4m
        exit 0
